spring.application.name=maven_app-repo-provider
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
dubbo.cloud.subscribed-services=-1
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


